---
title: "Sobre o O portal da Transparência"
---

## Header

O portal da Transparência tem informações sobre o orçamento executado pela Unirio em 2016. A fonte dos dados é SIAFI.

Nesse site temos quatro abas: 1 - Gráfico; 2 - Banco de Dados; 3 - Nota explicativa; e 4 - Análise do Orçamento. 

Na primeira aba temos dois tipos de gráficos. Esses dois gráficos são interativos. isso é, podem ser modificados no sidebar "Comandos dos Gráficos".  O primeiro tipo é chamado de Treemap onde o tamanho da área representa o valor gasto. Já o segundo, permite comparar o valor empenhado, liquidado e pago.Na segunda aba, podemos visualizar o banco de dados e sua estrutura. Para ver todo o banco de dados é necessário arrastar a barra lateral até o fim. Como é um banco de dados com 108 linhas, podemos arrasta-lo até esse número. Na terceira aba, tento apresentar uma nota explicativa com os principais conceitos do orçamento público. Nesse item há o glossário explicando o que é um empenho e o que são as categorias de análise possíveis (exemplo: o que é o Elemento de despesa ). Finalmente, na última aba, há um exemplo de análise do orçamento de 2016 e um infográfico com alguns resultados.


O site pode ser visto nesse link: https://duttross.shinyapps.io/transparencia1/


