---
title: "QUAL O ORÇAMENTO QUE VOCÊ FARIA PARA A UNIRIO?"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Todo mundo tem uma opinião sobre o que deveria ser feito nas finanças da nossa universidade. Aqui está a sua chance de experimentar/testar as suas idéias. O valor total empenhado pela Unirio em 2016 foi de 365 milhões (R$ 365.246.317,17)*. 

Este simulador foi construído para ilustrar as difíceis escolhas do orçamento para promover um diálogo público sobre o orçamento. Como serão as suas escolhas? Neste espaço você pode criar o seu próprio orçamento da Universidade.

#### Como esse site funciona?

Vamos te dar 365 milhões de reais. Isso representa 100% do orçamento. O seu trabalho será balancear o orçamento para financiar as muitas atividades importantes da Universidade.  Daremos algumas diretrizes - o  que acontece se você lhes usar mais - ou menos - dinheiro?

#### Existem algumas regras.

Queremos que você construa um orçamento da Universidade realista que possa funcionar na vida real. Financiamentos, como FAPERJ, CNPQ e Editais, estão fora dos limites. Você deve equilibrar o orçamento em 100%, mas pode ficar abaixo desse número.

#### Quanto tempo leva para fazer um orçamento?

Normalmente cerca de 10 minutos. Depende de quão bem você gostaria de entender cada categoria do orçamento antes de alocar o financiamento. Você pode ainda ver o portal da transparência, bem como decidir participar de pesquisas, etc.

#### O que acontece com os dados e as informações?

Vamos compilar o seu orçamento com os orçamentos de centenas de outros atores da Unirio. Depois de analisar os dados, vamos relatar o meta-orçamento - o orçamento da pessoas - para a gestão. (Esse projeto não identifica as pessoas e não divulga nenhuma informação pessoal).

Você será capaz de ver como a comunidade da Unirio querem gastar o dinheiro da Universidade versus como a administração realmente define o orçamento para esse ano. O que é o mesmo? O que é diferente? Mais importante - como esta informação pode ajudar a gestão a criar um orçamento melhor?

Parece interessante, como posso participar?
<br>
<a href="https://duttross.shinyapps.io/Engajamento/" class="btn btn-default">Início</a>

OBS -  A gestão da Universidade não poder modificar uma parte desse valor (por exemplo, o vencimento dos funcionários). Nessa comparação, somente as categorias discricionárias serão utilizadas.

OBS - 2 - Para participar da pesquisa clique [aqui](https://goo.gl/forms/3JwY301qMFqrgMya2)


<a href="#top">Back to top</a>